server:
  port: 8080
spring:
  application:
    name: day01
  datasource:
    url: jdbc:mysql://localhost:3306/car_battery_warning_db?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 768260
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

snowflake:
  data-center-id: 1
  worker-id: 1


